version: '3'

networks:
  app-net:
    external: true
    name: app

services:
  postgresql:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    container_name: postgres
    networks:
      - app-net
    env_file:
      - .env.postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  payment:
    image: wss:pay
    container_name: payment
    networks:
      - app-net
    restart: on-failure
    env_file:
      - .env.payment
    depends_on:
      - postgresql

  backend:
    image: back:TEST
    container_name: backend
    networks:
      - app-net
    depends_on:
      - postgresql
    ports:
      - 8000:8000
    env_file:
      - .env.backend
    volumes:
      - staticfiles:/var/www/static
  metabase:
      image: metabase/metabase:v0.56.19.x
      container_name: metabase
      networks:
        - app-net
      ports:
        - "3000:3000"
      env_file:
        - .env.metabase
      depends_on:
        - postgresql

volumes:
  postgres-data:
    driver: local
  staticfiles:
    external: true
